development:
  broker_uri: amqp://user:pass@rabbitmq-host/vhost
  broker_queue: metador.v1
  path_mappings:
    - from: /home/files
      to:  /mnt/files
    - from: /tmp/uploads
      to: /mnt/uploads

test:

production:
  broker_uri: amqp://user:pass@rabbitmq-host/vhost
  broker_queue: metador.v1
  path_mappings:
    - from: /home/files
      to:  /mnt/files
    - from: /tmp/uploads
      to: /mnt/uploads
